/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard/attendance'
import { Route as DashboardParentsRouteImport } from './routes/dashboard/parents'
import { Route as ApiStorageKeyRouteImport } from './routes/api/storage/$key'
import { Route as DashboardGroupsIndexRouteImport } from './routes/dashboard/groups/index'
import { Route as DashboardGroupsNewRouteImport } from './routes/dashboard/groups/new'
import { Route as DashboardSessionsIndexRouteImport } from './routes/dashboard/sessions/index'
import { Route as DashboardStudentsIndexRouteImport } from './routes/dashboard/students/index'
import { Route as DashboardStudentsNewRouteImport } from './routes/dashboard/students/new'
import { Route as DashboardTeachersIndexRouteImport } from './routes/dashboard/teachers/index'
import { Route as DashboardTeachersNewRouteImport } from './routes/dashboard/teachers/new'
import { Route as DashboardGroupsGroupTypeIndexRouteImport } from './routes/dashboard/groups/$groupType/index'
import { Route as DashboardGroupsGroupTypeEditRouteImport } from './routes/dashboard/groups/$groupType/edit'
import { Route as DashboardGroupsGroupTypeNewRouteImport } from './routes/dashboard/groups/$groupType/new'
import { Route as DashboardSessionsSessionIdIndexRouteImport } from './routes/dashboard/sessions/$sessionId/index'
import { Route as DashboardStudentsIdIndexRouteImport } from './routes/dashboard/students/$id/index'
import { Route as DashboardStudentsIdEditRouteImport } from './routes/dashboard/students/$id/edit'
import { Route as DashboardTeachersIdIndexRouteImport } from './routes/dashboard/teachers/$id/index'
import { Route as DashboardTeachersIdEditRouteImport } from './routes/dashboard/teachers/$id/edit'
import { Route as DashboardGroupsGroupTypeGroupNumberIndexRouteImport } from './routes/dashboard/groups/$groupType/$groupNumber/index'
import { Route as DashboardGroupsGroupTypeGroupNumberEditRouteImport } from './routes/dashboard/groups/$groupType/$groupNumber/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardParentsRoute = DashboardParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiStorageKeyRoute = ApiStorageKeyRouteImport.update({
  id: '/api/storage/$key',
  path: '/api/storage/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardGroupsIndexRoute = DashboardGroupsIndexRouteImport.update({
  id: '/groups/',
  path: '/groups/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsNewRoute = DashboardGroupsNewRouteImport.update({
  id: '/groups/new',
  path: '/groups/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSessionsIndexRoute = DashboardSessionsIndexRouteImport.update({
  id: '/sessions/',
  path: '/sessions/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsIndexRoute = DashboardStudentsIndexRouteImport.update({
  id: '/students/',
  path: '/students/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStudentsNewRoute = DashboardStudentsNewRouteImport.update({
  id: '/students/new',
  path: '/students/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeachersIndexRoute = DashboardTeachersIndexRouteImport.update({
  id: '/teachers/',
  path: '/teachers/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeachersNewRoute = DashboardTeachersNewRouteImport.update({
  id: '/teachers/new',
  path: '/teachers/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsGroupTypeIndexRoute =
  DashboardGroupsGroupTypeIndexRouteImport.update({
    id: '/groups/$groupType/',
    path: '/groups/$groupType/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGroupsGroupTypeEditRoute =
  DashboardGroupsGroupTypeEditRouteImport.update({
    id: '/groups/$groupType/edit',
    path: '/groups/$groupType/edit',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGroupsGroupTypeNewRoute =
  DashboardGroupsGroupTypeNewRouteImport.update({
    id: '/groups/$groupType/new',
    path: '/groups/$groupType/new',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardSessionsSessionIdIndexRoute =
  DashboardSessionsSessionIdIndexRouteImport.update({
    id: '/sessions/$sessionId/',
    path: '/sessions/$sessionId/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentsIdIndexRoute =
  DashboardStudentsIdIndexRouteImport.update({
    id: '/students/$id/',
    path: '/students/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardStudentsIdEditRoute = DashboardStudentsIdEditRouteImport.update({
  id: '/students/$id/edit',
  path: '/students/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardTeachersIdIndexRoute =
  DashboardTeachersIdIndexRouteImport.update({
    id: '/teachers/$id/',
    path: '/teachers/$id/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardTeachersIdEditRoute = DashboardTeachersIdEditRouteImport.update({
  id: '/teachers/$id/edit',
  path: '/teachers/$id/edit',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGroupsGroupTypeGroupNumberIndexRoute =
  DashboardGroupsGroupTypeGroupNumberIndexRouteImport.update({
    id: '/groups/$groupType/$groupNumber/',
    path: '/groups/$groupType/$groupNumber/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardGroupsGroupTypeGroupNumberEditRoute =
  DashboardGroupsGroupTypeGroupNumberEditRouteImport.update({
    id: '/groups/$groupType/$groupNumber/edit',
    path: '/groups/$groupType/$groupNumber/edit',
    getParentRoute: () => DashboardRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/parents': typeof DashboardParentsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/storage/$key': typeof ApiStorageKeyRoute
  '/dashboard/groups/new': typeof DashboardGroupsNewRoute
  '/dashboard/students/new': typeof DashboardStudentsNewRoute
  '/dashboard/teachers/new': typeof DashboardTeachersNewRoute
  '/dashboard/groups/': typeof DashboardGroupsIndexRoute
  '/dashboard/sessions/': typeof DashboardSessionsIndexRoute
  '/dashboard/students/': typeof DashboardStudentsIndexRoute
  '/dashboard/teachers/': typeof DashboardTeachersIndexRoute
  '/dashboard/groups/$groupType/edit': typeof DashboardGroupsGroupTypeEditRoute
  '/dashboard/groups/$groupType/new': typeof DashboardGroupsGroupTypeNewRoute
  '/dashboard/students/$id/edit': typeof DashboardStudentsIdEditRoute
  '/dashboard/teachers/$id/edit': typeof DashboardTeachersIdEditRoute
  '/dashboard/groups/$groupType/': typeof DashboardGroupsGroupTypeIndexRoute
  '/dashboard/sessions/$sessionId/': typeof DashboardSessionsSessionIdIndexRoute
  '/dashboard/students/$id/': typeof DashboardStudentsIdIndexRoute
  '/dashboard/teachers/$id/': typeof DashboardTeachersIdIndexRoute
  '/dashboard/groups/$groupType/$groupNumber/edit': typeof DashboardGroupsGroupTypeGroupNumberEditRoute
  '/dashboard/groups/$groupType/$groupNumber/': typeof DashboardGroupsGroupTypeGroupNumberIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/parents': typeof DashboardParentsRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/storage/$key': typeof ApiStorageKeyRoute
  '/dashboard/groups/new': typeof DashboardGroupsNewRoute
  '/dashboard/students/new': typeof DashboardStudentsNewRoute
  '/dashboard/teachers/new': typeof DashboardTeachersNewRoute
  '/dashboard/groups': typeof DashboardGroupsIndexRoute
  '/dashboard/sessions': typeof DashboardSessionsIndexRoute
  '/dashboard/students': typeof DashboardStudentsIndexRoute
  '/dashboard/teachers': typeof DashboardTeachersIndexRoute
  '/dashboard/groups/$groupType/edit': typeof DashboardGroupsGroupTypeEditRoute
  '/dashboard/groups/$groupType/new': typeof DashboardGroupsGroupTypeNewRoute
  '/dashboard/students/$id/edit': typeof DashboardStudentsIdEditRoute
  '/dashboard/teachers/$id/edit': typeof DashboardTeachersIdEditRoute
  '/dashboard/groups/$groupType': typeof DashboardGroupsGroupTypeIndexRoute
  '/dashboard/sessions/$sessionId': typeof DashboardSessionsSessionIdIndexRoute
  '/dashboard/students/$id': typeof DashboardStudentsIdIndexRoute
  '/dashboard/teachers/$id': typeof DashboardTeachersIdIndexRoute
  '/dashboard/groups/$groupType/$groupNumber/edit': typeof DashboardGroupsGroupTypeGroupNumberEditRoute
  '/dashboard/groups/$groupType/$groupNumber': typeof DashboardGroupsGroupTypeGroupNumberIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/parents': typeof DashboardParentsRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/storage/$key': typeof ApiStorageKeyRoute
  '/dashboard/groups/new': typeof DashboardGroupsNewRoute
  '/dashboard/students/new': typeof DashboardStudentsNewRoute
  '/dashboard/teachers/new': typeof DashboardTeachersNewRoute
  '/dashboard/groups/': typeof DashboardGroupsIndexRoute
  '/dashboard/sessions/': typeof DashboardSessionsIndexRoute
  '/dashboard/students/': typeof DashboardStudentsIndexRoute
  '/dashboard/teachers/': typeof DashboardTeachersIndexRoute
  '/dashboard/groups/$groupType/edit': typeof DashboardGroupsGroupTypeEditRoute
  '/dashboard/groups/$groupType/new': typeof DashboardGroupsGroupTypeNewRoute
  '/dashboard/students/$id/edit': typeof DashboardStudentsIdEditRoute
  '/dashboard/teachers/$id/edit': typeof DashboardTeachersIdEditRoute
  '/dashboard/groups/$groupType/': typeof DashboardGroupsGroupTypeIndexRoute
  '/dashboard/sessions/$sessionId/': typeof DashboardSessionsSessionIdIndexRoute
  '/dashboard/students/$id/': typeof DashboardStudentsIdIndexRoute
  '/dashboard/teachers/$id/': typeof DashboardTeachersIdIndexRoute
  '/dashboard/groups/$groupType/$groupNumber/edit': typeof DashboardGroupsGroupTypeGroupNumberEditRoute
  '/dashboard/groups/$groupType/$groupNumber/': typeof DashboardGroupsGroupTypeGroupNumberIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/attendance'
    | '/dashboard/parents'
    | '/dashboard/'
    | '/api/storage/$key'
    | '/dashboard/groups/new'
    | '/dashboard/students/new'
    | '/dashboard/teachers/new'
    | '/dashboard/groups/'
    | '/dashboard/sessions/'
    | '/dashboard/students/'
    | '/dashboard/teachers/'
    | '/dashboard/groups/$groupType/edit'
    | '/dashboard/groups/$groupType/new'
    | '/dashboard/students/$id/edit'
    | '/dashboard/teachers/$id/edit'
    | '/dashboard/groups/$groupType/'
    | '/dashboard/sessions/$sessionId/'
    | '/dashboard/students/$id/'
    | '/dashboard/teachers/$id/'
    | '/dashboard/groups/$groupType/$groupNumber/edit'
    | '/dashboard/groups/$groupType/$groupNumber/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard/attendance'
    | '/dashboard/parents'
    | '/dashboard'
    | '/api/storage/$key'
    | '/dashboard/groups/new'
    | '/dashboard/students/new'
    | '/dashboard/teachers/new'
    | '/dashboard/groups'
    | '/dashboard/sessions'
    | '/dashboard/students'
    | '/dashboard/teachers'
    | '/dashboard/groups/$groupType/edit'
    | '/dashboard/groups/$groupType/new'
    | '/dashboard/students/$id/edit'
    | '/dashboard/teachers/$id/edit'
    | '/dashboard/groups/$groupType'
    | '/dashboard/sessions/$sessionId'
    | '/dashboard/students/$id'
    | '/dashboard/teachers/$id'
    | '/dashboard/groups/$groupType/$groupNumber/edit'
    | '/dashboard/groups/$groupType/$groupNumber'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/dashboard/attendance'
    | '/dashboard/parents'
    | '/dashboard/'
    | '/api/storage/$key'
    | '/dashboard/groups/new'
    | '/dashboard/students/new'
    | '/dashboard/teachers/new'
    | '/dashboard/groups/'
    | '/dashboard/sessions/'
    | '/dashboard/students/'
    | '/dashboard/teachers/'
    | '/dashboard/groups/$groupType/edit'
    | '/dashboard/groups/$groupType/new'
    | '/dashboard/students/$id/edit'
    | '/dashboard/teachers/$id/edit'
    | '/dashboard/groups/$groupType/'
    | '/dashboard/sessions/$sessionId/'
    | '/dashboard/students/$id/'
    | '/dashboard/teachers/$id/'
    | '/dashboard/groups/$groupType/$groupNumber/edit'
    | '/dashboard/groups/$groupType/$groupNumber/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiStorageKeyRoute: typeof ApiStorageKeyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/parents': {
      id: '/dashboard/parents'
      path: '/parents'
      fullPath: '/dashboard/parents'
      preLoaderRoute: typeof DashboardParentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/storage/$key': {
      id: '/api/storage/$key'
      path: '/api/storage/$key'
      fullPath: '/api/storage/$key'
      preLoaderRoute: typeof ApiStorageKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/groups/': {
      id: '/dashboard/groups/'
      path: '/groups'
      fullPath: '/dashboard/groups/'
      preLoaderRoute: typeof DashboardGroupsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups/new': {
      id: '/dashboard/groups/new'
      path: '/groups/new'
      fullPath: '/dashboard/groups/new'
      preLoaderRoute: typeof DashboardGroupsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sessions/': {
      id: '/dashboard/sessions/'
      path: '/sessions'
      fullPath: '/dashboard/sessions/'
      preLoaderRoute: typeof DashboardSessionsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students/': {
      id: '/dashboard/students/'
      path: '/students'
      fullPath: '/dashboard/students/'
      preLoaderRoute: typeof DashboardStudentsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students/new': {
      id: '/dashboard/students/new'
      path: '/students/new'
      fullPath: '/dashboard/students/new'
      preLoaderRoute: typeof DashboardStudentsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teachers/': {
      id: '/dashboard/teachers/'
      path: '/teachers'
      fullPath: '/dashboard/teachers/'
      preLoaderRoute: typeof DashboardTeachersIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teachers/new': {
      id: '/dashboard/teachers/new'
      path: '/teachers/new'
      fullPath: '/dashboard/teachers/new'
      preLoaderRoute: typeof DashboardTeachersNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups/$groupType/': {
      id: '/dashboard/groups/$groupType/'
      path: '/groups/$groupType'
      fullPath: '/dashboard/groups/$groupType/'
      preLoaderRoute: typeof DashboardGroupsGroupTypeIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups/$groupType/edit': {
      id: '/dashboard/groups/$groupType/edit'
      path: '/groups/$groupType/edit'
      fullPath: '/dashboard/groups/$groupType/edit'
      preLoaderRoute: typeof DashboardGroupsGroupTypeEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups/$groupType/new': {
      id: '/dashboard/groups/$groupType/new'
      path: '/groups/$groupType/new'
      fullPath: '/dashboard/groups/$groupType/new'
      preLoaderRoute: typeof DashboardGroupsGroupTypeNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/sessions/$sessionId/': {
      id: '/dashboard/sessions/$sessionId/'
      path: '/sessions/$sessionId'
      fullPath: '/dashboard/sessions/$sessionId/'
      preLoaderRoute: typeof DashboardSessionsSessionIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students/$id/': {
      id: '/dashboard/students/$id/'
      path: '/students/$id'
      fullPath: '/dashboard/students/$id/'
      preLoaderRoute: typeof DashboardStudentsIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/students/$id/edit': {
      id: '/dashboard/students/$id/edit'
      path: '/students/$id/edit'
      fullPath: '/dashboard/students/$id/edit'
      preLoaderRoute: typeof DashboardStudentsIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teachers/$id/': {
      id: '/dashboard/teachers/$id/'
      path: '/teachers/$id'
      fullPath: '/dashboard/teachers/$id/'
      preLoaderRoute: typeof DashboardTeachersIdIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/teachers/$id/edit': {
      id: '/dashboard/teachers/$id/edit'
      path: '/teachers/$id/edit'
      fullPath: '/dashboard/teachers/$id/edit'
      preLoaderRoute: typeof DashboardTeachersIdEditRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups/$groupType/$groupNumber/': {
      id: '/dashboard/groups/$groupType/$groupNumber/'
      path: '/groups/$groupType/$groupNumber'
      fullPath: '/dashboard/groups/$groupType/$groupNumber/'
      preLoaderRoute: typeof DashboardGroupsGroupTypeGroupNumberIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/groups/$groupType/$groupNumber/edit': {
      id: '/dashboard/groups/$groupType/$groupNumber/edit'
      path: '/groups/$groupType/$groupNumber/edit'
      fullPath: '/dashboard/groups/$groupType/$groupNumber/edit'
      preLoaderRoute: typeof DashboardGroupsGroupTypeGroupNumberEditRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardParentsRoute: typeof DashboardParentsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGroupsNewRoute: typeof DashboardGroupsNewRoute
  DashboardStudentsNewRoute: typeof DashboardStudentsNewRoute
  DashboardTeachersNewRoute: typeof DashboardTeachersNewRoute
  DashboardGroupsIndexRoute: typeof DashboardGroupsIndexRoute
  DashboardSessionsIndexRoute: typeof DashboardSessionsIndexRoute
  DashboardStudentsIndexRoute: typeof DashboardStudentsIndexRoute
  DashboardTeachersIndexRoute: typeof DashboardTeachersIndexRoute
  DashboardGroupsGroupTypeEditRoute: typeof DashboardGroupsGroupTypeEditRoute
  DashboardGroupsGroupTypeNewRoute: typeof DashboardGroupsGroupTypeNewRoute
  DashboardStudentsIdEditRoute: typeof DashboardStudentsIdEditRoute
  DashboardTeachersIdEditRoute: typeof DashboardTeachersIdEditRoute
  DashboardGroupsGroupTypeIndexRoute: typeof DashboardGroupsGroupTypeIndexRoute
  DashboardSessionsSessionIdIndexRoute: typeof DashboardSessionsSessionIdIndexRoute
  DashboardStudentsIdIndexRoute: typeof DashboardStudentsIdIndexRoute
  DashboardTeachersIdIndexRoute: typeof DashboardTeachersIdIndexRoute
  DashboardGroupsGroupTypeGroupNumberEditRoute: typeof DashboardGroupsGroupTypeGroupNumberEditRoute
  DashboardGroupsGroupTypeGroupNumberIndexRoute: typeof DashboardGroupsGroupTypeGroupNumberIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardParentsRoute: DashboardParentsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGroupsNewRoute: DashboardGroupsNewRoute,
  DashboardStudentsNewRoute: DashboardStudentsNewRoute,
  DashboardTeachersNewRoute: DashboardTeachersNewRoute,
  DashboardGroupsIndexRoute: DashboardGroupsIndexRoute,
  DashboardSessionsIndexRoute: DashboardSessionsIndexRoute,
  DashboardStudentsIndexRoute: DashboardStudentsIndexRoute,
  DashboardTeachersIndexRoute: DashboardTeachersIndexRoute,
  DashboardGroupsGroupTypeEditRoute: DashboardGroupsGroupTypeEditRoute,
  DashboardGroupsGroupTypeNewRoute: DashboardGroupsGroupTypeNewRoute,
  DashboardStudentsIdEditRoute: DashboardStudentsIdEditRoute,
  DashboardTeachersIdEditRoute: DashboardTeachersIdEditRoute,
  DashboardGroupsGroupTypeIndexRoute: DashboardGroupsGroupTypeIndexRoute,
  DashboardSessionsSessionIdIndexRoute: DashboardSessionsSessionIdIndexRoute,
  DashboardStudentsIdIndexRoute: DashboardStudentsIdIndexRoute,
  DashboardTeachersIdIndexRoute: DashboardTeachersIdIndexRoute,
  DashboardGroupsGroupTypeGroupNumberEditRoute:
    DashboardGroupsGroupTypeGroupNumberEditRoute,
  DashboardGroupsGroupTypeGroupNumberIndexRoute:
    DashboardGroupsGroupTypeGroupNumberIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiStorageKeyRoute: ApiStorageKeyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
